### ISSUE TITLE
Price display and appropriate unit for ETH

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/crypto-storefront#13]
When setting the ETH price on the product to 1, the price of the product is displayed like this:

- Product overview: 1 ETH
- Product detail page: 0.01 ETH 
- Cart: 0.01 ETH
- Pay with Metamask: 1 ETH

Make sure that you re-use the same component to display a price in all components and change it in a way that the system treats ETH prices in an appropriate small unit, I select like this because we don't have BigInt support yet:

JS safe integer max: 9'007'199'254'740'991
Max cart price to represent: 1'000'000'000 USD equivalent
Currently translates to 872513 ETH

![Bildschirmfoto 2022-07-11 um 11 51 47](https://user-images.githubusercontent.com/2109393/178238308-d8942a5f-83c7-442b-8baa-2e5844832d79.png)

- 872'513'000'000 Szabo -> lower than Number.MAX_SAFE_INTEGER
- 872'513'000'000'000 GWEI -> lower than Number.MAX_SAFE_INTEGER
- 872'513'000'000'000'000 MWEI -> higher than Number.MAX_SAFE_INTEGER

-> thus i'd recommend to treat the ETH price as GWEI, so if I wanted to represent 1 ETH in the admin ui, i need to enter 1000000000

**Comment by pozylon** [comment]
For ERC-20 tokens that are custom I'd go for a 1 to 1 representation which will not allow somebody to accept a price like 5.5 SHIB but I think that's okay.

**Comment by Mikearaya** [comment]
GWEI is still large for graphql Int which only supports 32 bit Int, so i think it should be Szabo

**Comment by pozylon** [comment]
I thought int is always 53bit max int in js, where did you read that it behaves differently on 32bit systems?

**Comment by pozylon** [comment]
Ah sorry graphql is the issue hmm 🤔

**Comment by Mikearaya** [comment]
@pozylon  I've used a different approach to get around the graphql constraint. extend price to hold another field `gweiAmount: String` now the storefront can display any value supported in the engine. 
please let me know if you see any pit fall with this approach

**Comment by pozylon** [comment]
closing this, but there is still one open ticket regarding product details not showing price.

**Comment by Mikearaya** [comment]
@pozylon it's implemented here, and we will remove it once implemented
