### ISSUE TITLE
Replace placeholder images with actual placeholder png's :)

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/crypto-storefront#18]
<img width="1436" alt="Bildschirmfoto 2022-08-16 um 09 37 32" src="https://user-images.githubusercontent.com/2109393/184824150-dad0a69b-fe18-4fa9-9b22-4cd5cfcda440.png">
<img width="699" alt="Bildschirmfoto 2022-08-16 um 09 37 40" src="https://user-images.githubusercontent.com/2109393/184824176-ecd98423-c074-4f22-b2dd-1d97f7dee719.png">

Better use:

https://www.custommousepad.com/image/cache/placeholder-600x315w.png

**Comment by pozylon** [comment]
Still shows glasses for products @Rdttkab

**Comment by Mikearaya** [comment]
@pozylon i don't think you have updated the storefront, it is not displayed now

**Comment by Mikearaya** [comment]
i've added it on the `upgrade-unchained`
