### ISSUE TITLE
Can't make it process the payment

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/crypto-storefront#20]
I've used:

CRYPTOPAY_ETH_XPUB=xpub6DCkxV3yvvk8eGye7t11DZ3vpWkJLxfqCiGdB6jieHXHDyzvZTVXG632jcoEPCw6NCPw2GqghAGjmqeXGnLEQEbGTAZSN8neBh3SAyVn5k9

Sign created the following public address:
0xF5F72AE7fa1fa990ebaF163208Ed7aD6a3f42DEA

And payment in goerli has been completed:
https://goerli.etherscan.io/tx/0x56b34400ff6d9c6c8de9bd2251d27cb415027d7e80b3eed803e91c0e3585eea2

**log output crypto gateway:**
```
Started processing block...
Started processing block...ode at  http://127.0.0.1:8555  successfully
Processing block from  None  to  6952992
Processing block from  b'6952992'  to  7187040
Processing
```

**log output go etc client**:
INFO [08-16|07:30:20.846] Imported new block headers               count=1664 elapsed=146.922ms number=7,382,688 hash=ae7771..8e3483 age=5d6h17m
INFO [08-16|07:30:23.750] Imported new block headers               count=132  elapsed=14.556ms  number=7,382,820 hash=deabd6..1d6e2f age=5d5h44m
INFO [08-16|07:30:23.751] Imported new block headers               count=2    elapsed="467.084µs" number=7,382,822 hash=7e4bde..1bc4b7 age=5d5h44m
INFO [08-16|07:30:24.571] Looking for peers                        peercount=1 tried=1 static=0
INFO [08-16|07:30:37.560] Looking for peers                        peercount=1 tried=1 static=0
INFO [08-16|07:30:48.554] Looking for peers                        peercount=1 tried=1 static=0
INFO [08-16|07:31:00.700] Looking for peers                        peercount=1 tried=1 static=0

Somehow it stopped importing new block headers at block 7382822

**Comment by pozylon** [comment]
It's probably related to using "light" sync mode which depends on people running so called "light" servers that are rarely available on test net's. I'm now going "snap" sync mode

**Comment by Mikearaya** [comment]
@pozylon if it starts processing block i don't think missing node is the issue. do you see connected to any peer node, in the logs?

**Comment by pozylon** [comment]
Latest block was:
```
INFO [08-16|07:30:23.751] Imported new block headers count=2 elapsed="467.084µs" number=7,382,822 hash=7e4bde..1bc4b7 age=5d5h44m
```

-> 5 days old, geth didn't get past this

**Comment by pozylon** [comment]
So I was connected to a peer but that peer was also behind
