### ISSUE TITLE
Checkout Flow

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/crypto-storefront#22]
**Case 1: Metamask**

On Cart, display Pay With Metamask, if clicked, show full screen backdrop, "waiting for metamask", after confirmation, show message: "your order is submitted, awaiting block confirmations". Auto refreshes and finds out when block is confirmed, then redirects to thank you page with payment done.

If rejected on metamask, keep cart a cart, show message "payment cancelled".

**Case 2: QR Code**

In the case of qr code payment, only show the QR code after "confirm order". The whole order fullfillment will be asynchronous because we don't know how and when the transactions gets confirmed and how long it can take on which blockchain.

Changes:

1. Do not show QR Code on checkout review page
2. Do not show Metamask button on thank you page, paying with QR code requires an order confirmation before
3. "Lock the screen" when paying with metmask (see Case 1)

**Comment by Mikearaya** [comment]
So with this flow, the QR code will only need to be displayed on the order detail page because a confirmation of order will redirect a user to thank you page too.
Since meta mask payment is removed from thank you page too.
