### ISSUE TITLE
Price missing on product detail page

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/crypto-storefront#24]
<img width="1534" alt="Bildschirmfoto 2022-08-24 um 20 41 44" src="https://user-images.githubusercontent.com/2109393/186498621-6deccb66-7e8d-41c7-ad4c-376795382e92.png">

+ use the no image placeholder on that page for all other no-image cases (consistency)

**Comment by Mikearaya** [comment]
it's displayed, on the `upgrade-unchained` branch. i'll see if there is any case where it might not

![Screenshot from 2022-08-24 21-51-37](https://user-images.githubusercontent.com/9751246/186499740-5e8a1d58-a1d5-4e4a-b344-dffb99449c95.png)
