### ISSUE TITLE
Fix Checkout Flow UX

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/crypto-storefront#25]
<img width="1534" alt="Bildschirmfoto 2022-08-24 um 20 47 25" src="https://user-images.githubusercontent.com/2109393/186498960-54f51cb1-be45-4d59-b2f8-0fc05c08001b.png">

1. Remove "vat included 7.7%" on the right
2. "Sign Up" tab  and "Register" button  is wrong naming (it's a guest checkout) because it's only a sign up if you click the bottom box "create account"
3. Login tab is active by default but the guest checkout should be active by default
4. It should not be possible to "Confirm order" when billing information is not provided (the guest form) but currently cou can confirm the order without providing e-mail or address

**Comment by pozylon** [comment]
-> It still says "Register" on the Button in the "New here" form.

**Comment by pozylon** [comment]
Remove "New here message"

**Comment by pozylon** [comment]
Another change:

1. Do not show an open delivery address form after filling in address in guest checkout, keep the process as is when using a login.22.  2. !2. [2. B2. i2. ldschirmfoto 2022-08-26 um 15 51 39](https://user-images.githubusercontent.com/2109393/186919014-d594a759-804d-4e83-85ac-7ae42c94923e.png) 
![Bildschirmfoto 2022-08-26 um 15 51 39](https://user-images.githubusercontent.com/2109393/186919014-d594a759-804d-4e83-85ac-7ae42c94923e.png)

**Comment by pozylon** [comment]
Second: The country is not stored correctly in guest checkout because in edit form, country is shown as "Please select..."

**Comment by pozylon** [comment]
I have temporarily removed billing address and delivery method.

**Comment by Mikearaya** [comment]
@pozylon The changes are added, can you please check

**Comment by pozylon** [comment]
Nice!
